print("\n")
print("Ejercicio 1:")
print("\n")
number0= input("Escribe un número:")
print(number0, type(number0))
print("\n")
number_1= int(input("Escribe un número entero:"))
print(number_1, (type(number_1)))
print("\n")
number_2= float(input("Escribe un número con decimal:"))
print(number_2,type(number_2))
print("\n")
print("\n")

print("Ejercicio 2:")
print("\n")
numero1= int(input("Escribe un número entero:"))
print("{0:5d}".format(numero1))
print("\n")
numero2= float(input("Escribe un número decimal:"))
print("{0:5f}".format(numero2))
print("\n")
print("\n")

print("Ejercicio 3:")
print("\n")